from dotenv import load_dotenv
from rich.markdown import Markdown
from rich.panel import Panel
from rich.prompt import Prompt
from rich.text import Text

from clearink.config import ENV_PATH
from clearink.message import extract_text_from_content
from clearink.user.console import console, render_lemon, LEMON_YELLOW
from clearink.user.output_format import format_response_text
from clearink.user import mode
from clearink.user.i18n import t, set_lang, get_lang


def _extract_response(messages: list) -> str | None:
    """Extract the final assistant text response from a message list.

    Walks messages in reverse to find the last assistant message that
    contains a plain string (not a list of tool-use blocks).
    """
    for msg in reversed(messages):
        if msg.get("role") != "assistant":
            continue
        content = msg.get("content")
        text = extract_text_from_content(content).strip()
        if text:
            return text
    return None


def _make_user_message(text: str) -> dict:
    """Wrap user text with current mode instructions as a prefix."""
    mode_prompt = mode.get_mode_prompt()
    if mode_prompt:
        prefixed = (
            f"[Mode {mode.get_mode()} instructions begin]\n"
            f"{mode_prompt}\n"
            f"[Mode {mode.get_mode()} instructions end]\n\n"
            f"{text}"
        )
    else:
        prefixed = text
    return {"role": "user", "content": prefixed}


# ── Setup wizard (first-time configuration) ───────────────────


def _setup_wizard() -> bool:
    """Detect whether .env exists. If not, run the first-time setup wizard.

    Collects API key and language preference, then generates .env
    with sensible defaults (DeepSeek endpoint, model, thinking config).

    Returns:
        True if setup completed or already configured.
        False if the user wants to quit (empty API key at prompt).
    """
    if ENV_PATH.exists():
        return True

    # ── Render startup page ─────────────────────────────
    console.print()
    title = Text(t("setup_title"), style=LEMON_YELLOW)
    console.print(Panel(title, width=_panel_width(), expand=False))
    console.print()
    console.print(f"  {t('setup_welcome')}")
    console.print()
    console.print(f"  [dim]{t('setup_provider_note')}[/dim]")
    console.print()

    # ── 1. API key ──────────────────────────────────────
    api_key = Prompt.ask(f"  {t('setup_api_key_prompt')}").strip()
    while not api_key:
        console.print(f"  [red]{t('setup_api_key_empty')}[/red]")
        api_key = Prompt.ask(f"  {t('setup_api_key_prompt')}").strip()
        if not api_key:
            continue

    console.print()

    # ── 2. Language ─────────────────────────────────────
    use_zh_raw = Prompt.ask(f"  {t('setup_lang_prompt')}", default="n").strip()
    use_zh = use_zh_raw.lower() in ("y", "yes")
    lang = "zh" if use_zh else "en"
    console.print()

    # ── 3. Generate .env ────────────────────────────────
    env_content = f"""# ClearInk Environment Configuration
# Generated by setup wizard.

# API Configuration
ANTHROPIC_API_KEY = {api_key}
ANTHROPIC_BASE_URL = https://api.deepseek.com/anthropic
MODEL = deepseek-v4-pro

# Thinking / Reasoning
THINKING_TYPE = enabled
THINKING_EFFORT = max

# Sub-Agent / Teammate Model
SUBAGENT_MODEL = deepseek-v4-flash

# Language
CLEARINK_LANG = {lang}
"""
    ENV_PATH.parent.mkdir(parents=True, exist_ok=True)
    ENV_PATH.write_text(env_content.strip() + "\n", encoding="utf-8")

    # ── 4. Reload env + set language ────────────────────
    load_dotenv(ENV_PATH, override=True)
    set_lang(lang)

    console.print(f"  [green]{t('setup_done')}[/green]")
    console.print()
    return True


# ── Input collection (reused by run() and /end restart) ───────

_RESTART_SENTINEL = "__RESTART__"
_EXIT_SENTINEL = "__EXIT__"

_EXIT_COMMANDS = {"/exit", "/quit", "exit", "quit"}
_END_COMMANDS = {"/end", "/clear", "/new", "/reset"}


# ── zh layout helpers (en path unaffected) ──────────────────

def _panel_width() -> int:
    """Panel width: wider for Chinese (CJK chars are double-width)."""
    return 52 if get_lang() == "zh" else 44


def _collect_inputs() -> tuple[int, str, bool] | str:
    """Collect mode, paper title, formula, and step preference.

    Returns:
        (mode_val, query_text, step_enabled) on success.
        _EXIT_SENTINEL if the user wants to quit.
    """
    # ── 1. Mode selection ─────────────────────────────────
    console.print()
    console.print(f"  [bold]{t('select_mode')}[/bold]")
    console.print(f"    [1] [bold]{t('mode1_label')}[/bold]")
    console.print(f"    [2] {t('mode2_label')}")
    console.print()

    raw_mode = Prompt.ask(f"  [dim]{t('mode_prompt')}[/dim]", default="1").strip()
    if raw_mode.lower() in _EXIT_COMMANDS:
        return _EXIT_SENTINEL

    cmd = mode.detect_mode_command(raw_mode)
    if cmd is not None:
        mode.set_mode(cmd)
    # else keep current mode (defaults to Mode 1)

    console.print(f"  [dim]Mode {mode.get_mode()} · {mode.get_mode_label()}[/dim]")
    console.print()

    # ── 2. Paper title ────────────────────────────────────
    title = Prompt.ask(f"  [bold]{t('paper_title')}[/bold]").strip()
    if title.lower() in _EXIT_COMMANDS:
        return _EXIT_SENTINEL

    # Allow mode switch via /mode N at title prompt
    cmd = mode.detect_mode_command(title)
    if cmd is not None:
        mode.set_mode(cmd)
        console.print(f"  [dim]{t('mode_switched')} Mode {mode.get_mode()} · {mode.get_mode_label()}[/dim]")
        console.print()
        title = Prompt.ask(f"  [bold]{t('paper_title')}[/bold]").strip()
        if title.lower() in _EXIT_COMMANDS:
            return _EXIT_SENTINEL

    if not title:
        console.print(f"[dim]{t('no_title')}[/dim]")
        return _EXIT_SENTINEL

    console.print()

    # ── 3. Formula / concept question ────────────────────
    second_prompt_text = mode.get_second_input_prompt()
    second_input = Prompt.ask(f"  [bold]{second_prompt_text}[/bold]").strip()
    if second_input.lower() in _EXIT_COMMANDS:
        return _EXIT_SENTINEL

    console.print()

    # ── 4. Step mode? ─────────────────────────────────────
    start_cmd = Prompt.ask(
        f"  [dim]{t('step_prompt')}[/dim]"
    ).strip()

    step_enabled = False
    if start_cmd.lower() == "/step":
        mode.set_step_mode(True)
        step_enabled = True
        console.print(f"  [dim]{t('step_enabled')}[/dim]")
    elif start_cmd.lower() in _EXIT_COMMANDS:
        return _EXIT_SENTINEL

    console.print()

    # ── Build query ───────────────────────────────────────
    query = mode.build_query(title, second_input)
    return mode.get_mode(), query, step_enabled


# ── Main entry point ──────────────────────────────────────────


def run(agent_loop) -> None:
    # ── Setup wizard (first-time only) ───────────────
    if not _setup_wizard():
        return

    # ── Welcome ──────────────────────────────────────────
    console.print()
    render_lemon()
    console.print()

    while True:
        # ── Collect inputs ────────────────────────────────
        result = _collect_inputs()
        if result == _EXIT_SENTINEL:
            break
        current_mode, query, step_enabled = result

        messages = [{"role": "user", "content": query}]

        # ── First query ───────────────────────────────────
        try:
            with console.status(f"[dim]{t('analyzing')}[/dim]", spinner="dots"):
                messages = agent_loop(messages)
        except Exception as exc:
            console.print(f"[red]Error:[/red] {exc}")
            continue

        response = _extract_response(messages)
        if response:
            console.print(Markdown(format_response_text(response)))
        else:
            console.print(f"[dim]{t('no_response')}[/dim]")

        # ── Step mode active? Enter step sub-loop ─────────
        if step_enabled:
            result = _run_step_loop(agent_loop, messages)
            if result == _EXIT_SENTINEL:
                break
            # result == _RESTART_SENTINEL → loop back to input collection
            mode.set_step_mode(False)  # clear for fresh round
            continue

        # ── Normal follow-up loop ─────────────────────────
        result = _followup_loop(agent_loop, messages)
        if result == _EXIT_SENTINEL:
            break
        # result == _RESTART_SENTINEL → loop back to input collection

    console.print(f"[dim]{t('session_ended')}[/dim]")


# ── Follow-up loop (non-step mode) ────────────────────────────


def _followup_loop(agent_loop, messages: list) -> str:
    """Normal follow-up loop. Returns _EXIT_SENTINEL or _RESTART_SENTINEL."""
    console.print(
        f"[dim]{t('followup_hint')}[/dim]"
    )

    while True:
        console.print()
        try:
            followup = Prompt.ask("[dim]>[/dim]").strip()
        except (KeyboardInterrupt, EOFError):
            console.print()
            return _RESTART_SENTINEL

        if followup.lower() in _EXIT_COMMANDS:
            return _EXIT_SENTINEL

        # ── /end — restart full input flow ────────────────
        if followup.lower() in _END_COMMANDS:
            console.print(f"[dim]{t('round_end')}[/dim]")
            return _RESTART_SENTINEL

        # ── /step — enter step mode for this follow-up ────
        if followup.lower() == "/step":
            mode.set_step_mode(True)
            console.print(f"[dim]{t('step_mode_hint')}[/dim]")
            result = _run_step_loop(agent_loop, messages)
            if result == _EXIT_SENTINEL:
                return _EXIT_SENTINEL
            mode.set_step_mode(False)
            return _RESTART_SENTINEL

        # ── Mode switch ───────────────────────────────────
        cmd = mode.detect_mode_command(followup)
        if cmd is not None:
            mode.set_mode(cmd)
            console.print(
                f"[dim]{t('mode_switched')} Mode {mode.get_mode()} · "
                f"{mode.get_mode_label()}[/dim]"
            )
            continue

        if not followup:
            continue

        # ── Normal agent call ─────────────────────────────
        msg = _make_user_message(followup)
        messages.append(msg)

        try:
            with console.status(f"[dim]{t('step_thinking')}[/dim]", spinner="dots"):
                messages = agent_loop(messages)
        except Exception as exc:
            console.print(f"[red]Error:[/red] {exc}")
            continue

        console.print()
        followup_response = _extract_response(messages)
        if followup_response:
            console.print(Markdown(format_response_text(followup_response)))


# ── Step sub-loop ─────────────────────────────────────────────


def _run_step_loop(agent_loop, messages: list) -> str:
    """Run step-mode interaction with hard-coded step progression.

    /next — advance to next step via mode.advance_step() (hard-coded).
    /end  — restart full input flow (returns _RESTART_SENTINEL).
    /exit — quit program (returns _EXIT_SENTINEL).

    Returns:
        _EXIT_SENTINEL if the user wants to quit.
        _RESTART_SENTINEL if the user wants a fresh round.
    """
    # Step 1 — first step
    step = mode.advance_step()
    step_msg = mode.get_step_instruction()
    messages.append({"role": "user", "content": step_msg})

    try:
        with console.status(f"[dim]Step {step} — {t('analyzing').lower()}[/dim]", spinner="dots"):
            messages[:] = agent_loop(messages)
    except Exception as exc:
        console.print(f"[red]Error:[/red] {exc}")
        return _RESTART_SENTINEL

    console.print()
    response = _extract_response(messages)
    if response:
        console.print(Markdown(format_response_text(response)))

    # Step sub-loop
    while True:
        console.print()
        try:
            cmd = Prompt.ask("[dim]step >[/dim]").strip()
        except (KeyboardInterrupt, EOFError):
            console.print()
            return _RESTART_SENTINEL

        # ── /end — restart full input flow ────────────────
        if cmd.lower() in _END_COMMANDS:
            console.print(f"[dim]{t('round_end')}[/dim]")
            return _RESTART_SENTINEL

        # ── /exit or /quit ────────────────────────────────
        if cmd.lower() in _EXIT_COMMANDS:
            return _EXIT_SENTINEL

        # ── Mode switch ───────────────────────────────────
        mode_cmd = mode.detect_mode_command(cmd)
        if mode_cmd is not None:
            mode.set_mode(mode_cmd)
            console.print(
                f"[dim]{t('mode_switched')} Mode {mode.get_mode()} · "
                f"{mode.get_mode_label()}[/dim]"
            )
            continue

        # ── /step — already in step mode ──────────────────
        if cmd.lower() == "/step":
            console.print(f"[dim]{t('already_step')}[/dim]")
            continue

        # ── /next — hard-coded step advancement ───────────
        if cmd.lower() == "/next":
            # After Step 2, capture the paper list from task system
            if mode.get_current_step() == 2:
                count = mode.capture_paper_tasks()
                if count == 0:
                    console.print(f"[dim]({t('no_reading_tasks')})[/dim]")

            step = mode.advance_step()
            step_msg = mode.get_step_instruction()
            messages.append({"role": "user", "content": step_msg})

            try:
                with console.status(
                    f"[dim]Step {step} — {t('step_thinking')}[/dim]", spinner="dots"
                ):
                    messages[:] = agent_loop(messages)
            except Exception as exc:
                console.print(f"[red]Error:[/red] {exc}")
                continue

            console.print()
            response = _extract_response(messages)
            if response:
                console.print(Markdown(format_response_text(response)))
            continue

        if not cmd:
            continue

        # ── Free text — new question within step mode ─────
        msg = _make_user_message(cmd)
        mode.reset_step_state()  # fresh step sequence
        step = mode.advance_step()
        msg["content"] = mode.get_step_instruction() + "\n\n" + msg["content"]
        messages.append(msg)

        try:
            with console.status(f"[dim]Step {step} — {t('analyzing').lower()}[/dim]", spinner="dots"):
                messages[:] = agent_loop(messages)
        except Exception as exc:
            console.print(f"[red]Error:[/red] {exc}")
            continue

        console.print()
        response = _extract_response(messages)
        if response:
            console.print(Markdown(format_response_text(response)))
        # stay in step sub-loop for /next or /end
